server:
  port: 8081

generator:
  enabled: true
  count: 1000
  batchSize: 10
  service-url: http://localhost:8080

worker:
  submit:
    delay-ms: 5000
    enabled: true
    batchSize: 10

  approve:
    delay-ms: 7000
    enabled: true
    batchSize: 10

#
#generator:
#  service-url: http://localhost:8080
#  batchSize: 100
#
#worker:
#  submit:
#    delay-ms: 5000
#  approve:
#    delay-ms: 7000